package com.crazylegend.vigilante.settings


/**
 * Created by crazy on 11/2/20 to long live and prosper !
 */

const val PREF_CATEGORY_KEY = "pref_category"
const val DOT_APPEARANCE = "dot_appearance"
const val NOTIFICATIONS_PREF_KEY = "pref_notifications"
const val THEME_PREF_KEY = "pref_theme"
const val BYPASS_DND_PREF_KEY = "pref_bypass_dnd"
const val VERSION_PREF_KEY = "pref_version"
const val DATE_PREF_KEY = "pref_date"
const val DOT_PREF_KEY = "pref_dot"
const val LANG_PREF_KEY = "pref_language"
const val HOME_PAGE_PREF = "pref_home_page"
const val MY_OTHER_APPS_PREF_KEY = "pref_my_other_apps"
const val NOTIFICATION_SOUNDS_KEY = "pref_sound"
const val EXCLUDE_VIGILANTE_FROM_NOTIFICATIONS_PREF_KEY = "pref_exclude_vigilante_from_notifications"
const val CAMERA_CUSTOMIZATION_BASE_PREF = "camera_"
const val MIC_CUSTOMIZATION_BASE_PREF = "mic_"
const val LOCATION_CUSTOMIZATION_BASE_PREF = "location_"
const val INTRO_PREF = "intro"
const val BIOMETRIC_AUTH_PREF_KEY = "pref_biometric_auth"
const val DELETE_HISTORY_PREF_KEY = "pref_delete_history"
const val DEFAULT_DATE_FORMAT = "dd.MM.yyyy HH:mm:ss"
const val LOG_PERMISSIONS_KEY = "pref_log_permissions"
const val LOG_EMPTY_PERMISSIONS_KEY = "pref_log_empty_notifications"
const val LOG_POWER_KEY = "pref_log_power"
const val LOG_HEADSET_KEY = "pref_log_headset"
const val LOG_NOTIFICATIONS_KEY = "pref_log_notifications"
const val LOG_LOCKSCREEN_KEY = "pref_log_lockscreen"
const val LOGGING_PREF = "pref_logging"

const val PREF_CATEGORY_CAMERA = CAMERA_CUSTOMIZATION_BASE_PREF + PREF_CATEGORY_KEY
const val CAMERA_DOT_APPEARANCE = CAMERA_CUSTOMIZATION_BASE_PREF + DOT_APPEARANCE
const val CAMERA_DOT_PREF_KEY = CAMERA_CUSTOMIZATION_BASE_PREF + DOT_PREF_KEY
const val CAMERA_BYPASS_DND_PREF_KEY = CAMERA_CUSTOMIZATION_BASE_PREF + BYPASS_DND_PREF_KEY
const val CAMERA_NOTIFICATIONS_PREF_KEY = CAMERA_CUSTOMIZATION_BASE_PREF + NOTIFICATIONS_PREF_KEY
const val CAMERA_SOUNDS_PREF_KEY = CAMERA_CUSTOMIZATION_BASE_PREF + NOTIFICATION_SOUNDS_KEY


const val PREF_CATEGORY_MIC = MIC_CUSTOMIZATION_BASE_PREF + PREF_CATEGORY_KEY
const val MIC_DOT_APPEARANCE = MIC_CUSTOMIZATION_BASE_PREF + DOT_APPEARANCE
const val MIC_DOT_PREF_KEY = MIC_CUSTOMIZATION_BASE_PREF + DOT_PREF_KEY
const val MIC_BYPASS_DND_PREF_KEY = MIC_CUSTOMIZATION_BASE_PREF + BYPASS_DND_PREF_KEY
const val MIC_NOTIFICATIONS_PREF_KEY = MIC_CUSTOMIZATION_BASE_PREF + NOTIFICATIONS_PREF_KEY
const val MIC_SOUNDS_PREF_KEY = MIC_CUSTOMIZATION_BASE_PREF + NOTIFICATION_SOUNDS_KEY


const val PREF_CATEGORY_LOCATION = LOCATION_CUSTOMIZATION_BASE_PREF + PREF_CATEGORY_KEY
const val LOCATION_DOT_APPEARANCE = LOCATION_CUSTOMIZATION_BASE_PREF + DOT_APPEARANCE
const val LOCATION_DOT_PREF_KEY = LOCATION_CUSTOMIZATION_BASE_PREF + DOT_PREF_KEY
const val LOCATION_BYPASS_DND_PREF_KEY = LOCATION_CUSTOMIZATION_BASE_PREF + BYPASS_DND_PREF_KEY
const val LOCATION_NOTIFICATIONS_PREF_KEY = LOCATION_CUSTOMIZATION_BASE_PREF + NOTIFICATIONS_PREF_KEY
const val LOCATION_SOUNDS_PREF_KEY = LOCATION_CUSTOMIZATION_BASE_PREF + NOTIFICATION_SOUNDS_KEY